### PR TITLE
[SOL] re-enable debug info on SBF

### PR DESCRIPTION
**Pull request by riptl**
Set `SupportsDebugInformation` to `true` for `sbf`.

### CODE REVIEW

**Comment by riptl** [comment]
There's probably a good reason why this was disabled in the first place. I've tested it with a C program and it works fine though.

**Comment by riptl** [comment]
Aha! `ld.lld: error: canvas.c:(.BTF.ext+0xC0): unrecognized reloc R_BPF_64_NODYLD32`

`sbf`/`bpfel+solana` doesn't support the `R_BPF_64_NODYLD32` [reloc](https://www.kernel.org/doc/html/latest/bpf/llvm_reloc.html) required for [BPF Type Format](https://www.kernel.org/doc/html/latest/bpf/btf.html) section. Looks like an easy fix though.

**Comment by riptl** [comment]
Another problem is this

https://github.com/solana-labs/llvm-project/blob/321d9c077f20a571f3ec7ba4513b78e7ccf13a71/llvm/lib/Target/BPF/MCTargetDesc/BPFELFObjectWriter.cpp#L97

This corrupts all relocs in the `.rel.debug_line` section, which need to be `R_BPF_64_ABS32`.

I patched that section by hand and got a working Solana `.so` program with full DWARF info and even a copy of the C source code included in the BTF section. 😃

**Comment by riptl** [comment]
Debug section relocs work now, @dmakarov would you mind taking a look?

**Comment by dmakarov** [comment]
Looks good, but I'll run a few more tests before I can merge this.

**Comment by riptl** [comment]
Thanks – one thing I was concerned about was relocs in the `.rodata` section. I've yet to test them, I hope I didn't break them.

**Comment by dmakarov** [comment]
I get the relocation error when a program is loaded to RBPF 
```
ELF error: Relocation failed, unknown type 2
```
Pretty much all our tests fail with this change.

If you want to test this, build solana-labs/rust with the `src/llvm-project` submodule updated to include your changes. Once you have the rust compiler binaries, make a symbolic link `rust` in `~/.cache/solana/v1.23/bpf-tools/` to point to `stage1/` subdir in your build of rust ( `rust/build/x86_64-apple-darwin/stage1`) and then run
```
cargo test --features="bpf_c,bpf_rust" -- --nocapture --test-threads=1
```
in `solana-labs/solana/programs/bpf`

**Comment by riptl** [comment]
Thanks for verifying, I will investigate this further then. The solution is probably to only use the `R_BPF_64_ABS32` relocs for debug sections and otherwise the `R_BPF_64_32` variant.

**Comment by riptl** [comment]
Moved over to #32

**Pull request closed without merging**
