### PR TITLE
[SOL] Fix bug in LLD that prevented linker from being called twice

### PR DESCRIPTION
**Pull request by LucasSte**
This PR is the same as https://github.com/solana-labs/llvm-project/pull/57, but for LLVM 15.

### CODE REVIEW

**Comment by dmakarov** [comment]
@LucasSte looks good. Do you want to make the PR ready for review and merge it? I'm planning a new release of sbf-tools and would like to include this in the release.

**Comment by LucasSte** [comment]
> @LucasSte looks good. Do you want to make the PR ready for review and merge it? I'm planning a new release of sbf-tools and would like to include this in the release.

Of course, we can merge this PR. It fixes the linker bug that still exists in LLVM 15.
Nonetheless, I haven't finished adapting Solang's code generation to LLVM 15 yet, as it requires major changes due to the introduction of opaque pointers. Although I linker bug is fixed, I am not sure if I am going to need further changes. When are you planning your release?

**Comment by dmakarov** [comment]
> > @LucasSte looks good. Do you want to make the PR ready for review and merge it? I'm planning a new release of sbf-tools and would like to include this in the release.
> 
> Of course, we can merge this PR. It fixes the linker bug that still exists in LLVM 15. Nonetheless, I haven't finished adapting Solang's code generation to LLVM 15 yet, as it requires major changes due to the introduction of opaque pointers. Although I linker bug is fixed, I am not sure if I am going to need further changes. When are you planning your release?

I would like to tag this repository for the release today. I can do it without this PR, so no rush, if you don't want to merge the PR yet.

**Comment by LucasSte** [comment]
> > > @LucasSte looks good. Do you want to make the PR ready for review and merge it? I'm planning a new release of sbf-tools and would like to include this in the release.
> > 
> > 
> > Of course, we can merge this PR. It fixes the linker bug that still exists in LLVM 15. Nonetheless, I haven't finished adapting Solang's code generation to LLVM 15 yet, as it requires major changes due to the introduction of opaque pointers. Although I linker bug is fixed, I am not sure if I am going to need further changes. When are you planning your release?
> 
> I would like to tag this repository for the release today. I can do it without this PR, so no rush, if you don't want to merge the PR yet.

@dmakarov Ready for review now!

**Review by dmakarov — APPROVED** [review]

**Pull request merged**
